### ISSUE TITLE
Required package helm-1.5.9 is unavailable

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [yasuyk/helm-company#12]
It looks like this package requires a specific version of `helm` or otherwise it complains. I usually install from a git clone, and I am getting this warning.

**Comment by yasuyk** [comment]
Sorry for the very very delayed response.
I bumped latest `helm-core` version at d196a50.

**Comment by amelio-vazquez-reina** [comment]
Thanks @yasuyk !
