### ISSUE TITLE
Use helm-company instead of company-mode completion popup

### ISSUE THREAD

**Issue by manuel-uberti** [yasuyk/helm-company#15]
This is more of a question than an issue related to ```helm-company```(which is working great, thanks for this package).

Whenever I am typing, ```company-mode``` starts completing showing the completion popup. Of course I can press the keybinding I set for ```helm-company```, but is it possible to hide the completion popup entirely and just complete through ```helm-company```?

**Comment by tuhdo** [comment]
Yes, you can, by setting `company-idle-delay` to `nil` and bind `helm-company` to a key and press it whenever you want completion.

**Comment by manuel-uberti** [comment]
Works like a charm, thank you very much.
