### ISSUE TITLE
helm-company insert wrong completion

### ISSUE THREAD

**Issue by s-kostyaev** [yasuyk/helm-company#22]
When I type "cus" and press M-: (helm-company) and select "custom-set-variables" the result is "cuscustom-set-variables". Current version from MELPA.

**Comment by s-kostyaev** [comment]
I think that problem is then helm company get variants executes function company-complete-common and cursor change position. This position changing does not calculates.

**Comment by yasuyk** [comment]
@s-kostyaev Sorry for the very very delayed response.

:smile: Thank you for reporting this issue. I merged your patch.

**Comment by s-kostyaev** [comment]
Thanks. I thoght that current mainstream is now manuel-uberti/helm-company.

**Comment by yasuyk** [comment]
@s-kostyaev Yes.  I noticed it after merged this patch ... So I make this repository obsolete ( See [README](https://github.com/yasuyk/helm-company/blob/fc912dc36750d719ecdbb12d8ebc0b2fe0cbf8cc/README.md)).
